# Generated by Django 4.1.2 on 2023-02-28 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_followerscount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowersCount',
        ),
    ]
